global:
    memo: snipeTR#8374-icq-rly-test
default_chain: gaia
chains:
  gaia:
    key: wallet
    chain-id: GAIA
    rpc-addr: http://192.168.0.61:23657
    grpc-addr: http://192.168.0.61:23090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.01uatom
    key-directory: /root/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride:
    key: wallet
    chain-id: STRIDE-TESTNET-2
    rpc-addr: http://127.0.0.1:26657
    grpc-addr: http://127.0.0.1:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.01ustrd
    key-directory: /root/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
